### ISSUE TITLE
Выбрать модели компонент (задний фон карты, модели основного корабля, вражеских кораблей, модели астероидов, модели препятствий, бонусы, получаемые в ходе игры) 

### ISSUE THREAD

**Issue by NekoRDAB** [NekoRDAB/igrulka#2]

**Comment by VladislavBukirev** [comment]
Background - https://assetstore.unity.com/packages/2d/textures-materials/dynamic-space-background-lite-104606#content

**Comment by VladislavBukirev** [comment]
Ships and background - 
https://assetstore.unity.com/packages/2d/environments/2d-space-kit-27662#content

**Comment by VladislavBukirev** [comment]
Menu buttons -
https://assetstore.unity.com/packages/2d/gui/sci-fi-gui-skin-15606
